CREATE TABLE IF NOT EXISTS Word(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(200) NOT NULL,
  definition TEXT NULL,
)

CREATE TABLE IF NOT EXISTS Score(
  wordid,
  lastTouched TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)

CREATE TABLE IF NOT EXISTS Sentence(

)